<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.7.7">
]
>

<object class="java.util.Vector" name="__root__" version="3.7.7">
   <object class="weka.classifiers.bayes.BayesNet" name="0">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-N</object>
         <object class="java.lang.String" name="5">-P</object>
         <object class="java.lang.String" name="6">1</object>
         <object class="java.lang.String" name="7">-S</object>
         <object class="java.lang.String" name="8">AIC</object>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="1">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-N</object>
         <object class="java.lang.String" name="5">-P</object>
         <object class="java.lang.String" name="6">1</object>
         <object class="java.lang.String" name="7">-S</object>
         <object class="java.lang.String" name="8">BAYES</object>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="2">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-N</object>
         <object class="java.lang.String" name="5">-P</object>
         <object class="java.lang.String" name="6">1</object>
         <object class="java.lang.String" name="7">-S</object>
         <object class="java.lang.String" name="8">BDeu</object>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="3">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-N</object>
         <object class="java.lang.String" name="5">-P</object>
         <object class="java.lang.String" name="6">1</object>
         <object class="java.lang.String" name="7">-S</object>
         <object class="java.lang.String" name="8">ENTROPY</object>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="4">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-N</object>
         <object class="java.lang.String" name="5">-P</object>
         <object class="java.lang.String" name="6">1</object>
         <object class="java.lang.String" name="7">-S</object>
         <object class="java.lang.String" name="8">MDL</object>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="5">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-N</object>
         <object class="java.lang.String" name="5">-P</object>
         <object class="java.lang.String" name="6">1</object>
         <object class="java.lang.String" name="7">-mbc</object>
         <object class="java.lang.String" name="8">-S</object>
         <object class="java.lang.String" name="9">AIC</object>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="6">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-N</object>
         <object class="java.lang.String" name="5">-P</object>
         <object class="java.lang.String" name="6">1</object>
         <object class="java.lang.String" name="7">-mbc</object>
         <object class="java.lang.String" name="8">-S</object>
         <object class="java.lang.String" name="9">BAYES</object>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="7">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-N</object>
         <object class="java.lang.String" name="5">-P</object>
         <object class="java.lang.String" name="6">1</object>
         <object class="java.lang.String" name="7">-mbc</object>
         <object class="java.lang.String" name="8">-S</object>
         <object class="java.lang.String" name="9">BDeu</object>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="8">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-N</object>
         <object class="java.lang.String" name="5">-P</object>
         <object class="java.lang.String" name="6">1</object>
         <object class="java.lang.String" name="7">-mbc</object>
         <object class="java.lang.String" name="8">-S</object>
         <object class="java.lang.String" name="9">ENTROPY</object>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="9">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-N</object>
         <object class="java.lang.String" name="5">-P</object>
         <object class="java.lang.String" name="6">1</object>
         <object class="java.lang.String" name="7">-mbc</object>
         <object class="java.lang.String" name="8">-S</object>
         <object class="java.lang.String" name="9">MDL</object>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="10">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-P</object>
         <object class="java.lang.String" name="5">1</object>
         <object class="java.lang.String" name="6">-S</object>
         <object class="java.lang.String" name="7">AIC</object>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="11">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-P</object>
         <object class="java.lang.String" name="5">1</object>
         <object class="java.lang.String" name="6">-S</object>
         <object class="java.lang.String" name="7">BAYES</object>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="12">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-P</object>
         <object class="java.lang.String" name="5">1</object>
         <object class="java.lang.String" name="6">-S</object>
         <object class="java.lang.String" name="7">BDeu</object>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="13">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-P</object>
         <object class="java.lang.String" name="5">1</object>
         <object class="java.lang.String" name="6">-S</object>
         <object class="java.lang.String" name="7">ENTROPY</object>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="14">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-P</object>
         <object class="java.lang.String" name="5">1</object>
         <object class="java.lang.String" name="6">-S</object>
         <object class="java.lang.String" name="7">MDL</object>
         <object class="java.lang.String" name="8"/>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="15">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-P</object>
         <object class="java.lang.String" name="5">1</object>
         <object class="java.lang.String" name="6">-mbc</object>
         <object class="java.lang.String" name="7">-S</object>
         <object class="java.lang.String" name="8">AIC</object>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>
         <object class="java.lang.String" name="24"/>
      </object>
   </object>
   <object class="weka.classifiers.bayes.BayesNet" name="16">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-D</object>
         <object class="java.lang.String" name="1">-Q</object>
         <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
         <object class="java.lang.String" name="3">--</object>
         <object class="java.lang.String" name="4">-P</object>
         <object class="java.lang.String" name="5">1</object>
         <object class="java.lang.String" name="6">-mbc</object>
         <object class="java.lang.String" name="7">-S</object>
         <object class="java.lang.String" name="8">BAYES</object>
         <object class="java.lang.String" name="9"/>
         <object class="java.lang.String" name="10"/>
         <object class="java.lang.String" name="11"/>
         <object class="java.lang.String" name="12"/>
         <object class="java.lang.String" name="13"/>
         <object class="java.lang.String" name="14"/>
         <object class="java.lang.String" name="15"/>
         <object class="java.lang.String" name="16">-E</object>
         <object class="java.lang.String" name="17">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
         <object class="java.lang.String" name="18">--</object>
         <object class="java.lang.String" name="19">-A</object>
         <object class="java.lang.String" name="20">0.5</object>
         <object class="java.lang.String" name="21"/>
         <object class="java.lang.String" name="22"/>
         <object class="java.lang.String" name="23"/>